services:
###This is my frontend con which is running nginx
  frontend:
    build: ./frontend
    ports:
      - "80:80"

###This is my frontend con which is running PHP
  backend:
    build: ./backend
    ports:
      - "8080:80"
    depends_on: 
      - frontend



###This is my frontend con which is running Database
  # db:
  #   build: ./db
  #   depends_on: 
  #     - backend